apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::705029535563:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-YBI5K64WSOKT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::705029535563:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-08T18:09:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1303"
  uid: ff384327-6389-4276-a235-1000789ea5b7
