apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::705029535563:role/eksctl-simple-jwt-api1-nodegroup-NodeInstanceRole-VECJLXYH6CX8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::705029535563:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-09T05:22:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1207"
  uid: a48e85e4-1e79-40be-813d-cf4b70f10329
